services:
  mysql:
    image: mysql/mysql-server:8.0
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    networks:
      - internal
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root123}
      MYSQL_DATABASE: fleet
      MYSQL_USER: fleet
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-fleet123}
      MYSQL_TLS_CONFIG: skip-verify
    expose:
      - 3306

  redis:
    image: redis:latest
    networks:
      - internal
    volumes:
      - redis:/data
    expose:
      - 6379

  fleet_oneshot:
    image: fleetdm/fleet:latest
    command: 'fleet prepare db'
    restart: 'no'
    networks:
      - internal
    environment: &fleet_environment
      FLEET_MYSQL_ADDRESS: mysql:3306
      FLEET_MYSQL_DATABASE: fleet
      FLEET_MYSQL_USERNAME: fleet
      FLEET_MYSQL_PASSWORD: ${MYSQL_PASSWORD:-fleet123}
      FLEET_REDIS_ADDRESS: redis:6379
      FLEET_SERVER_TLS: false
      FLEET_OSQUERY_POLICY_UPDATE_INTERVAL: 30s

  fleet:
    image: fleetdm/fleet:latest
    volumes:
      - type: bind
        source: ./fleet
        target: /fleet
    environment: *fleet_environment
    networks:
      - reverse-proxy
      - internal
    # ports:
    #   - "8412:8080"
    depends_on:
      fleet_oneshot:
        condition: service_completed_successfully

volumes:
  mysql:
  redis:

networks:
  internal:
  reverse-proxy:
    external: true